import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Router from 'next/router';
import { getAuth, signInAnonymously, onAuthStateChanged } from "firebase/auth";
import { getFirestore, addDoc, setDoc, doc, collection, getDoc, getDocs } from "firebase/firestore";
import { app } from '../firebase.config';

const auth = getAuth(app);
const db = getFirestore(app);

export default function Home() {
  const [courses, setCourses] = React.useState([]);

  React.useEffect(() => {
    const getCourses = async () => {
      const courses = [];
      const querySnapshot = await getDocs(collection(db, "courses"));
      querySnapshot.forEach((doc) => {
        const data = doc.data();
        data.id = doc.id;
        courses.push(data);
      });
      setCourses(courses);
    };
    getCourses();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Cursuri Dragos Catalin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="py-6">
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {courses.map((course) => (
            <div key={course.id} className="cursor-pointer overflow-hidden transition-all transform bg-white rounded-lg shadow-sm dark:bg-gray-800 hover:scale-105 w-full"
              onClick={() => Router.push(`/course/${course.id}`)}
            >
              <img className="object-cover w-full h-56" src={course.image} alt="" />
              <div className="p-4">
                <h4 className="mb-2 text-lg font-semibold text-gray-800 dark:text-gray-300">
                  {course.title}
                </h4>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  {course.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </main>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
